# EJEMPLO DE PROYECTO FINAL
# AUTOR: César Mayta
# DATASET : https://www.kaggle.com/code/adilshamim8/eda-on-data-science-salaries

# INSTALAMOS LIBRERIAS

In [1]:
!pip install pyjanitor
import janitor

Collecting pyjanitor
  Downloading pyjanitor-0.31.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: natsort in /usr/local/lib/python3.11/dist-packages (from pyjanitor) (8.4.0)
Collecting pandas_flavor (from pyjanitor)
  Downloading pandas_flavor-0.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.11/dist-packages (from pyjanitor) (1.0.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pyjanitor) (1.16.1)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.11/dist-packages (from pandas_flavor->pyjanitor) (2.2.2)
Requirement already satisfied: xarray in /usr/local/lib/python3.11/dist-packages (from pandas_flavor->pyjanitor) (2025.7.1)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.11/dist-packages (from scipy->pyjanitor) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas_flavor->pyjanitor) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas_flavor->pyjanitor) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas_flavor->pyjanitor) (2025.2)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.11/dist-packages (from xarray->pandas_flavor->pyjanitor) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_flavor->pyjanitor) (1.17.0)
Downloading pyjanitor-0.31.0-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.4/215.4 kB 7.4 MB/s eta 0:00:00
Downloading pandas_flavor-0.7.0-py3-none-any.whl (8.4 kB)
Installing collected packages: pandas_flavor, pyjanitor
Successfully installed pandas_flavor-0.7.0 pyjanitor-0.31.0

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sns.set(style='whitegrid',context='notebook')

# CARGAMOS DATASET

In [15]:
path = '/content/salaries.csv'
df = pd.read_csv(path)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M
...,...,...,...,...,...,...,...,...,...,...,...
151440,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
151441,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
151442,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
151443,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
151444,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

# EDA

In [16]:
df.dtypes.value_counts()

object    7
int64     4
Name: count, dtype: int64

In [17]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [18]:
df_cleaned = df.drop(columns=['work_year', 'salary', 'salary_currency'])

In [19]:
df_cleaned

,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,EX,FT,Head of Data,348516,US,0,US,M
1,EX,FT,Head of Data,232344,US,0,US,M
2,SE,FT,Data Scientist,145400,US,0,US,M
3,SE,FT,Data Scientist,81600,US,0,US,M
4,MI,FT,Engineer,160000,US,100,US,M
...,...,...,...,...,...,...,...,...
151440,SE,FT,Data Scientist,412000,US,100,US,L
151441,MI,FT,Principal Data Scientist,151000,US,100,US,L
151442,EN,FT,Data Scientist,105000,US,100,US,S
151443,EN,CT,Business Data Analyst,100000,US,100,US,L
151444,SE,FT,Data Scientist,94665,IN,50,IN,L

In [20]:
object_cols = df_cleaned.select_dtypes(include='object').columns

for col in object_cols:
    print(f"Value counts for column: {col}")
    print(df_cleaned[col].value_counts())
    print("-" * 30)

Value counts for column: experience_level
experience_level
SE    87491
MI    46128
EN    13663
EX     4163
Name: count, dtype: int64
------------------------------
Value counts for column: employment_type
employment_type
FT    150541
CT       467
PT       421
FL        16
Name: count, dtype: int64
------------------------------
Value counts for column: job_title
job_title
Data Scientist                      18751
Software Engineer                   16948
Data Engineer                       16352
Data Analyst                        13779
Engineer                            11004
                                    ...
AI Software Development Engineer        1
Quantitative Research Analyst           1
CRM Data Analyst                        1
Principal Data Architect                1
Cloud Data Architect                    1
Name: count, Length: 422, dtype: int64
------------------------------
Value counts for column: employee_residence
employee_residence
US    135506
CA      6207
GB      4172
AU       590
NL       482
       ...
KW         1
AS         1
CN         1
IQ         1
JE         1
Name: count, Length: 104, dtype: int64
------------------------------
Value counts for column: company_location
company_location
US    135569
CA      6208
GB      4181
AU       595
NL       482
       ...
IR         1
BS         1
IQ         1
CN         1
MD         1
Name: count, Length: 97, dtype: int64
------------------------------
Value counts for column: company_size
company_size
M    147302
L      3926
S       217
Name: count, dtype: int64
------------------------------

In [30]:
data_job_titles = df[df['job_title'].str.contains('Data Analyst', na=False)]
display(data_job_titles['job_title'].value_counts())

job_title
Data Analyst                          13779
Business Data Analyst                    21
BI Data Analyst                          19
Admin & Data Analyst                      6
Lead Data Analyst                         6
Product Data Analyst                      6
Financial Data Analyst                    4
Finance Data Analyst                      3
Staff Data Analyst                        3
Compliance Data Analyst                   2
Marketing Data Analyst                    2
Principal Data Analyst                    2
Data Analyst Lead                         2
Business Intelligence Data Analyst        2
BI & Data Analyst                         1
Fraud Data Analyst                        1
Advanced Data Analyst                     1
People Data Analyst                       1
Big Data Analyst                          1
CRM Data Analyst                          1
Sales Data Analyst                        1
Name: count, dtype: int64

In [29]:
data_job_titles = df[df['job_title'].str.contains('Data Architect', na=False)]
display(data_job_titles['job_title'].value_counts())

job_title
Data Architect                  2216
Big Data Architect                 2
IT Enterprise Data Architect       1
AWS Data Architect                 1
Principal Data Architect           1
Cloud Data Architect               1
Name: count, dtype: int64

In [31]:
data_job_titles = df[df['job_title'].str.contains('Scientis', na=False)]
display(data_job_titles['job_title'].value_counts())

job_title
Data Scientist                        18751
Research Scientist                     3460
Applied Scientist                      2381
Machine Learning Scientist              537
Decision Scientist                      216
AI Scientist                            138
Bioinformatics Scientist                 86
ML Scientist                             48
Principal Scientist                      36
Computational Scientist                  18
Applied Machine Learning Scientist       14
Applied Data Scientist                   13
AI Data Scientist                        12
Lead Data Scientist                      11
Principal Data Scientist                 10
AI Research Scientist                     8
Data Scientist Lead                       3
Staff Data Scientist                      3
Cheminformatics Scientist                 2
Data Scientist Manager                    2
Applied Research Scientist                2
Data Scientist Expert                     1
Data Scientist Associate                  1
Marketing Data Scientist                  1
Name: count, dtype: int64

In [32]:
non_data_job_titles = df[~df['job_title'].str.contains('Data', na=False)]
display(non_data_job_titles['job_title'].value_counts())

job_title
Software Engineer                  16948
Engineer                           11004
Machine Learning Engineer           8887
Manager                             7811
Analyst                             5396
                                   ...
Business Insights Manager              1
Controls Engineer                      1
Staff Machine Learning Engineer        1
Analytics Engineering Manager          1
Deep Learning Researcher               1
Name: count, Length: 262, dtype: int64

In [33]:
def classify_job_title(title):
    if 'Data Analyst' in title:
        return 'Data Analyst'
    elif 'Data Engineer' in title or 'Data Architect' in title:
        return 'Data Engineer'
    elif 'Data Scientist' in title or 'Scientist' in title:
        return 'Data Scientist'
    elif 'Data' not in title:
        return 'Software Engineer'
    else:
        return 'Engineer' # Keep any other job titles that contain 'Data' but don't fit the above

df['job_title'] = df['job_title'].apply(classify_job_title)
display(df['job_title'].value_counts())

job_title
Software Engineer    85135
Data Scientist       25754
Data Engineer        18615
Data Analyst         13864
Engineer              8077
Name: count, dtype: int64

## ANALISIS DE PAISES

In [40]:
import kagglehub

# Download latest version
country_path = kagglehub.dataset_download("andradaolteanu/country-mapping-iso-continent-region")

print("Path to dataset files:", country_path)

Path to dataset files: /kaggle/input/country-mapping-iso-continent-region

In [41]:
!ls -lh {country_path}

total 20K
-rw-r--r-- 1 1000 1000 20K Aug 19 01:51 continents2.csv

In [43]:
COUNTRY_FULL_PATH = country_path + '/continents2.csv'
df_paises = pd.read_csv(COUNTRY_FULL_PATH)
df_paises = df_paises[['alpha-2','region','sub-region']]

In [55]:
df_paises['sub-region'].value_counts()

sub-region
Sub-Saharan Africa                 53
Latin America and the Caribbean    52
Western Asia                       18
Southern Europe                    16
Northern Europe                    16
South-eastern Asia                 11
Eastern Europe                     10
Polynesia                          10
Southern Asia                       9
Western Europe                      9
Eastern Asia                        8
Micronesia                          8
Northern Africa                     7
Australia and New Zealand           6
Northern America                    5
Melanesia                           5
Central Asia                        5
Name: count, dtype: int64

In [52]:
df_paises[df_paises['region'] == 'Americas']['sub-region'].unique()

array(['Latin America and the Caribbean', 'Northern America'],
      dtype=object)

In [ ]:
europe_countries = df_paises[df_paises['sub-region'] == 'Latin America and the Caribbean']['alpha-2'].tolist()
europe_countries

In [56]:
def classify_zona(row):
    if row['region'] != 'Americas':
        return row['region']
    else:
        if row['sub-region'] == 'Latin America and the Caribbean':
            return 'Latin America'
        elif row['sub-region'] == 'Northern America':
            return 'NorthAmerica'
        else:
            return row['region']

df_paises['zona'] = df_paises.apply(classify_zona, axis=1)
display(df_paises.head())

  alpha-2   region       sub-region     zona
0      AF     Asia    Southern Asia     Asia
1      AX   Europe  Northern Europe   Europe
2      AL   Europe  Southern Europe   Europe
3      DZ   Africa  Northern Africa   Africa
4      AS  Oceania        Polynesia  Oceania

In [57]:
df_paises['zona'].value_counts()

zona
Africa           60
Latin America    52
Europe           51
Asia             51
Oceania          29
NorthAmerica      5
Name: count, dtype: int64

In [58]:
df_cleaned = df_cleaned.merge(df_paises[['alpha-2', 'zona']], left_on='employee_residence', right_on='alpha-2', how='left')
df_cleaned = df_cleaned.drop(columns='alpha-2')
df_cleaned = df_cleaned.rename(columns={'zona': 'pais_empleado'})
display(df_cleaned.head())

,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,pais_empleado
0,EX,FT,Head of Data,348516,US,0,US,M,NorthAmerica
1,EX,FT,Head of Data,232344,US,0,US,M,NorthAmerica
2,SE,FT,Data Scientist,145400,US,0,US,M,NorthAmerica
3,SE,FT,Data Scientist,81600,US,0,US,M,NorthAmerica
4,MI,FT,Engineer,160000,US,100,US,M,NorthAmerica

In [59]:
df_cleaned['pais_empleado'].value_counts()

pais_empleado
NorthAmerica     141714
Europe             7845
Oceania             671
Asia                584
Latin America       460
Africa              169
Name: count, dtype: int64

In [60]:
df_cleaned = df_cleaned.merge(df_paises[['alpha-2', 'zona']], left_on='company_location', right_on='alpha-2', how='left')
df_cleaned = df_cleaned.drop(columns='alpha-2')
df_cleaned = df_cleaned.rename(columns={'zona': 'pais_empleador'})
display(df_cleaned.head())

,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,pais_empleado,pais_empleador
0,EX,FT,Head of Data,348516,US,0,US,M,NorthAmerica,NorthAmerica
1,EX,FT,Head of Data,232344,US,0,US,M,NorthAmerica,NorthAmerica
2,SE,FT,Data Scientist,145400,US,0,US,M,NorthAmerica,NorthAmerica
3,SE,FT,Data Scientist,81600,US,0,US,M,NorthAmerica,NorthAmerica
4,MI,FT,Engineer,160000,US,100,US,M,NorthAmerica,NorthAmerica

In [62]:
df_cleaned[df_cleaned['pais_empleado'] =='Latin America']

,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,pais_empleado,pais_empleador
2048,SE,FT,Solution Architect,108007,CO,0,CO,M,Latin America,Latin America
2049,SE,FT,Solution Architect,63655,CO,0,CO,M,Latin America,Latin America
2402,SE,FT,Data Architect,120384,AR,100,AR,M,Latin America,Latin America
2403,SE,FT,Data Architect,90288,AR,100,AR,M,Latin America,Latin America
3849,MI,FT,Automation Engineer,90000,AR,100,AR,M,Latin America,Latin America
...,...,...,...,...,...,...,...,...,...,...
151294,SE,FT,Data Engineer,33511,MX,0,MX,S,Latin America,Latin America
151336,SE,FT,Lead Data Engineer,160000,PR,50,US,S,Latin America,NorthAmerica
151354,EN,FT,Machine Learning Engineer,21844,CO,50,CO,M,Latin America,Latin America
151366,MI,FT,Data Scientist,40038,CL,100,CL,L,Latin America,Latin America
151414,SE,FT,Computer Vision Engineer,18907,BR,0,BR,M,Latin America,Latin America

In [64]:
df_processed = df_cleaned[['experience_level','employment_type','job_title','salary_in_usd','remote_ratio','company_size','pais_empleado','pais_empleador']]

In [65]:
df_processed.dtypes

experience_level    object
employment_type     object
job_title           object
salary_in_usd        int64
remote_ratio         int64
company_size        object
pais_empleado       object
pais_empleador      object
dtype: object

In [72]:
df_processed = df_processed.dropna()

In [73]:
df_processed.isna().sum()

experience_level    0
employment_type     0
job_title           0
salary_in_usd       0
remote_ratio        0
company_size        0
pais_empleado       0
pais_empleador      0
dtype: int64

In [77]:
def classify_job_title(title):
    if 'Data Analyst' in title:
        return 'Data Analyst'
    elif 'Data Engineer' in title or 'Data Architect' in title:
        return 'Data Engineer'
    elif 'Data Scientist' in title or 'Scientist' in title:
        return 'Data Scientist'
    elif 'Data' not in title:
        return 'Software Engineer'
    else:
        return 'Engineer' # Keep any other job titles that contain 'Data' but don't fit the above

df_processed['position'] = df_processed['job_title'].apply(classify_job_title)
display(df_processed['position'].value_counts())

position
Software Engineer    85133
Data Scientist       25754
Data Engineer        18615
Data Analyst         13864
Engineer              8077
Name: count, dtype: int64

In [79]:
df_processed = df_processed[['experience_level','employment_type','position','salary_in_usd','remote_ratio','company_size','pais_empleado','pais_empleador']]
df_processed

,experience_level,employment_type,position,salary_in_usd,remote_ratio,company_size,pais_empleado,pais_empleador
0,EX,FT,Engineer,348516,0,M,NorthAmerica,NorthAmerica
1,EX,FT,Engineer,232344,0,M,NorthAmerica,NorthAmerica
2,SE,FT,Data Scientist,145400,0,M,NorthAmerica,NorthAmerica
3,SE,FT,Data Scientist,81600,0,M,NorthAmerica,NorthAmerica
4,MI,FT,Software Engineer,160000,100,M,NorthAmerica,NorthAmerica
...,...,...,...,...,...,...,...,...
151440,SE,FT,Data Scientist,412000,100,L,NorthAmerica,NorthAmerica
151441,MI,FT,Data Scientist,151000,100,L,NorthAmerica,NorthAmerica
151442,EN,FT,Data Scientist,105000,100,S,NorthAmerica,NorthAmerica
151443,EN,CT,Data Analyst,100000,100,L,NorthAmerica,NorthAmerica
151444,SE,FT,Data Scientist,94665,50,L,Asia,Asia

In [80]:
object_cols = df_processed.select_dtypes(include='object').columns

for col in object_cols:
    print(f"Value counts for column: {col}")
    print(df_processed[col].value_counts())
    print("-" * 30)

Value counts for column: experience_level
experience_level
SE    87491
MI    46126
EN    13663
EX     4163
Name: count, dtype: int64
------------------------------
Value counts for column: employment_type
employment_type
FT    150539
CT       467
PT       421
FL        16
Name: count, dtype: int64
------------------------------
Value counts for column: position
position
Software Engineer    85133
Data Scientist       25754
Data Engineer        18615
Data Analyst         13864
Engineer              8077
Name: count, dtype: int64
------------------------------
Value counts for column: company_size
company_size
M    147300
L      3926
S       217
Name: count, dtype: int64
------------------------------
Value counts for column: pais_empleado
pais_empleado
NorthAmerica     141714
Europe             7845
Oceania             671
Asia                584
Latin America       460
Africa              169
Name: count, dtype: int64
------------------------------
Value counts for column: pais_empleador
pais_empleador
NorthAmerica     141777
Europe             7838
Oceania             679
Asia                539
Latin America       449
Africa              161
Name: count, dtype: int64
------------------------------

In [82]:
categorical_columns = df_processed.select_dtypes(object).columns

In [83]:
ordinal_cols = ['company_size']
onehot_cols = list(set(categorical_columns) - set(ordinal_cols))
onehot_cols

['employment_type',
 'pais_empleador',
 'pais_empleado',
 'experience_level',
 'position']

In [95]:
df_processed

,experience_level,employment_type,position,salary_in_usd,remote_ratio,company_size,pais_empleado,pais_empleador
0,EX,FT,Engineer,348516,0,M,NorthAmerica,NorthAmerica
1,EX,FT,Engineer,232344,0,M,NorthAmerica,NorthAmerica
2,SE,FT,Data Scientist,145400,0,M,NorthAmerica,NorthAmerica
3,SE,FT,Data Scientist,81600,0,M,NorthAmerica,NorthAmerica
4,MI,FT,Software Engineer,160000,100,M,NorthAmerica,NorthAmerica
...,...,...,...,...,...,...,...,...
151440,SE,FT,Data Scientist,412000,100,L,NorthAmerica,NorthAmerica
151441,MI,FT,Data Scientist,151000,100,L,NorthAmerica,NorthAmerica
151442,EN,FT,Data Scientist,105000,100,S,NorthAmerica,NorthAmerica
151443,EN,CT,Data Analyst,100000,100,L,NorthAmerica,NorthAmerica
151444,SE,FT,Data Scientist,94665,50,L,Asia,Asia

In [96]:
df_processed.to_csv('job_salary_clean.csv',index=False,encoding='utf-8')

In [97]:
data_df_clean = pd.read_csv('job_salary_clean.csv')
data_df_clean

,experience_level,employment_type,position,salary_in_usd,remote_ratio,company_size,pais_empleado,pais_empleador
0,EX,FT,Engineer,348516,0,M,NorthAmerica,NorthAmerica
1,EX,FT,Engineer,232344,0,M,NorthAmerica,NorthAmerica
2,SE,FT,Data Scientist,145400,0,M,NorthAmerica,NorthAmerica
3,SE,FT,Data Scientist,81600,0,M,NorthAmerica,NorthAmerica
4,MI,FT,Software Engineer,160000,100,M,NorthAmerica,NorthAmerica
...,...,...,...,...,...,...,...,...
151438,SE,FT,Data Scientist,412000,100,L,NorthAmerica,NorthAmerica
151439,MI,FT,Data Scientist,151000,100,L,NorthAmerica,NorthAmerica
151440,EN,FT,Data Scientist,105000,100,S,NorthAmerica,NorthAmerica
151441,EN,CT,Data Analyst,100000,100,L,NorthAmerica,NorthAmerica
151442,SE,FT,Data Scientist,94665,50,L,Asia,Asia

In [98]:
categorical_columns = data_df_clean.select_dtypes(object).columns
categorical_columns

Index(['experience_level', 'employment_type', 'position', 'company_size',
       'pais_empleado', 'pais_empleador'],
      dtype='object')

In [99]:
for cc in categorical_columns:
  print("*"*50)
  print(data_df_clean[cc].value_counts())

**************************************************
experience_level
SE    87491
MI    46126
EN    13663
EX     4163
Name: count, dtype: int64
**************************************************
employment_type
FT    150539
CT       467
PT       421
FL        16
Name: count, dtype: int64
**************************************************
position
Software Engineer    85133
Data Scientist       25754
Data Engineer        18615
Data Analyst         13864
Engineer              8077
Name: count, dtype: int64
**************************************************
company_size
M    147300
L      3926
S       217
Name: count, dtype: int64
**************************************************
pais_empleado
NorthAmerica     141714
Europe             7845
Oceania             671
Asia                584
Latin America       460
Africa              169
Name: count, dtype: int64
**************************************************
pais_empleador
NorthAmerica     141777
Europe             7838
Oceania             679
Asia                539
Latin America       449
Africa              161
Name: count, dtype: int64

In [100]:
ordinal_cols = ['company_size']
onehot_cols = list(set(categorical_columns) - set(ordinal_cols))
onehot_cols

['employment_type',
 'pais_empleador',
 'pais_empleado',
 'experience_level',
 'position']

In [101]:
import sklearn.compose
import sklearn.preprocessing

In [102]:
transformer = sklearn.compose.make_column_transformer(
    (sklearn.preprocessing.OrdinalEncoder(),ordinal_cols),
    (sklearn.preprocessing.OneHotEncoder(),onehot_cols),
    remainder='passthrough'
)
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinalencoder', OrdinalEncoder(),
                                 ['company_size']),
                                ('onehotencoder', OneHotEncoder(),
                                 ['employment_type', 'pais_empleador',
                                  'pais_empleado', 'experience_level',
                                  'position'])])

In [105]:
data_transformed = transformer.fit_transform(data_df_clean)

In [106]:
# si es sparse convertirlo a array
if hasattr(data_transformed, "toarray"):
    data_transformed = data_transformed.toarray()

In [107]:
data_transformed_df = pd.DataFrame(
    data_transformed,
    columns=transformer.get_feature_names_out(),
    index=data_df_clean.index
)

In [108]:
data_transformed_df

,ordinalencoder__company_size,onehotencoder__employment_type_CT,onehotencoder__employment_type_FL,onehotencoder__employment_type_FT,onehotencoder__employment_type_PT,onehotencoder__pais_empleador_Africa,onehotencoder__pais_empleador_Asia,onehotencoder__pais_empleador_Europe,onehotencoder__pais_empleador_Latin America,onehotencoder__pais_empleador_NorthAmerica,...,onehotencoder__experience_level_EX,onehotencoder__experience_level_MI,onehotencoder__experience_level_SE,onehotencoder__position_Data Analyst,onehotencoder__position_Data Engineer,onehotencoder__position_Data Scientist,onehotencoder__position_Engineer,onehotencoder__position_Software Engineer,remainder__salary_in_usd,remainder__remote_ratio
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,348516.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,232344.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,145400.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,81600.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,160000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151438,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,412000.0,100.0
151439,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,151000.0,100.0
151440,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,105000.0,100.0
151441,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,100000.0,100.0
151442,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,94665.0,50.0

In [109]:
data_transformed_df = data_transformed_df.rename(
    columns=lambda x: x.replace("ordinalencoder__", "").replace("onehotencoder__", "").replace("remainder__", "")
)

data_transformed_df

,company_size,employment_type_CT,employment_type_FL,employment_type_FT,employment_type_PT,pais_empleador_Africa,pais_empleador_Asia,pais_empleador_Europe,pais_empleador_Latin America,pais_empleador_NorthAmerica,...,experience_level_EX,experience_level_MI,experience_level_SE,position_Data Analyst,position_Data Engineer,position_Data Scientist,position_Engineer,position_Software Engineer,salary_in_usd,remote_ratio
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,348516.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,232344.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,145400.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,81600.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,160000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151438,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,412000.0,100.0
151439,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,151000.0,100.0
151440,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,105000.0,100.0
151441,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,100000.0,100.0
151442,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,94665.0,50.0

In [110]:
data_transformed_df = (
    data_transformed_df.clean_names(
        case_type="snake"
    )
)
data_transformed_df.columns

Index(['company_size', 'employment_type_ct', 'employment_type_fl',
       'employment_type_ft', 'employment_type_pt', 'pais_empleador_africa',
       'pais_empleador_asia', 'pais_empleador_europe',
       'pais_empleador_latin_america', 'pais_empleador_north_america',
       'pais_empleador_oceania', 'pais_empleado_africa', 'pais_empleado_asia',
       'pais_empleado_europe', 'pais_empleado_latin_america',
       'pais_empleado_north_america', 'pais_empleado_oceania',
       'experience_level_en', 'experience_level_ex', 'experience_level_mi',
       'experience_level_se', 'position_data_analyst',
       'position_data_engineer', 'position_data_scientist',
       'position_engineer', 'position_software_engineer', 'salary_in_usd',
       'remote_ratio'],
      dtype='object')

In [111]:
data_transformed_df = data_transformed_df.rename(
    columns=lambda x: x.replace("employment_type_", "tipo_")
    .replace("pais_empleador_", "empleador_")
    .replace("pais_empleado_", "empleado_")
    .replace("experience_level_", "seniority_")
)
data_transformed_df

,company_size,tipo_ct,tipo_fl,tipo_ft,tipo_pt,empleador_africa,empleador_asia,empleador_europe,empleador_latin_america,empleador_north_america,...,seniority_ex,seniority_mi,seniority_se,position_data_analyst,position_data_engineer,position_data_scientist,position_engineer,position_software_engineer,salary_in_usd,remote_ratio
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,348516.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,232344.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,145400.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,81600.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,160000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151438,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,412000.0,100.0
151439,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,151000.0,100.0
151440,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,105000.0,100.0
151441,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,100000.0,100.0
151442,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,94665.0,50.0

In [112]:
data_transformed_df = data_transformed_df.rename(
    columns={
        "salary_in_usd":"salary"
    }
)
data_transformed_df.columns

Index(['company_size', 'tipo_ct', 'tipo_fl', 'tipo_ft', 'tipo_pt',
       'empleador_africa', 'empleador_asia', 'empleador_europe',
       'empleador_latin_america', 'empleador_north_america',
       'empleador_oceania', 'empleado_africa', 'empleado_asia',
       'empleado_europe', 'empleado_latin_america', 'empleado_north_america',
       'empleado_oceania', 'seniority_en', 'seniority_ex', 'seniority_mi',
       'seniority_se', 'position_data_analyst', 'position_data_engineer',
       'position_data_scientist', 'position_engineer',
       'position_software_engineer', 'salary', 'remote_ratio'],
      dtype='object')

In [113]:
data_transformed_df

,company_size,tipo_ct,tipo_fl,tipo_ft,tipo_pt,empleador_africa,empleador_asia,empleador_europe,empleador_latin_america,empleador_north_america,...,seniority_ex,seniority_mi,seniority_se,position_data_analyst,position_data_engineer,position_data_scientist,position_engineer,position_software_engineer,salary,remote_ratio
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,348516.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,232344.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,145400.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,81600.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,160000.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151438,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,412000.0,100.0
151439,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,151000.0,100.0
151440,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,105000.0,100.0
151441,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,100000.0,100.0
151442,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,94665.0,50.0

In [114]:
data_transformed_df.to_csv('salary_data_transformed.csv',index=False,encoding='utf-8')