In [1]:
import pandas as pd
df_books = pd.read_csv('https://github.com/cesarmayta/datasets/raw/refs/heads/main/libros.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

# GROUP BY

In [9]:
df_books.groupby('Author').sum().reset_index()

,Author,Name,User Rating,Reviews,Price,Year,Genre
0,Abraham Verghese,Cutting for StoneCutting for Stone,9.2,9732,22,4021,FictionFiction
1,Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
2,Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
3,Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
4,Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...,...
243,Walter Isaacson,Leonardo da VinciSteve JobsSteve Jobs,13.7,18668,61,6040,Non FictionNon FictionNon Fiction
244,William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",8.8,14994,12,4025,Non FictionNon Fiction
245,William P. Young,The Shack: Where Tragedy Confronts EternityThe...,9.2,39440,16,4026,FictionFiction
246,Wizards RPG Team,Player's Handbook (Dungeons & Dragons)Player's...,14.4,50970,81,6054,FictionFictionFiction
247,Zhi Gang Sha,Divine Soul Mind Body Healing and Transmission...,9.2,257,23,4022,Non FictionNon Fiction

In [10]:
df_books.groupby('Author')[['User Rating','Reviews','Price']].mean().reset_index()

                         Author  User Rating       Reviews      Price
0              Abraham Verghese     4.600000   4866.000000  11.000000
1                Adam Gasiewski     4.400000   3113.000000   6.000000
2                 Adam Mansbach     4.800000   9568.000000   9.000000
3                     Adir Levy     4.800000   8170.000000  13.000000
4    Admiral William H. McRaven     4.700000  10199.000000  11.000000
..                          ...          ...           ...        ...
243             Walter Isaacson     4.566667   6222.666667  20.333333
244               William Davis     4.400000   7497.000000   6.000000
245            William P. Young     4.600000  19720.000000   8.000000
246            Wizards RPG Team     4.800000  16990.000000  27.000000
247                Zhi Gang Sha     4.600000    128.500000  11.500000

[248 rows x 4 columns]

# AGG - AGREGACIONES

In [12]:
df_books.groupby('Author')[['User Rating','Reviews','Price']].agg(['min','mean','max']).reset_index()

                         Author User Rating                Reviews  \
                                        min      mean  max     min
0              Abraham Verghese         4.6  4.600000  4.6    4866
1                Adam Gasiewski         4.4  4.400000  4.4    3113
2                 Adam Mansbach         4.8  4.800000  4.8    9568
3                     Adir Levy         4.8  4.800000  4.8    8170
4    Admiral William H. McRaven         4.7  4.700000  4.7   10199
..                          ...         ...       ...  ...     ...
243             Walter Isaacson         4.5  4.566667  4.6    3014
244               William Davis         4.4  4.400000  4.4    7497
245            William P. Young         4.6  4.600000  4.6   19720
246            Wizards RPG Team         4.8  4.800000  4.8   16990
247                Zhi Gang Sha         4.6  4.600000  4.6      37

                         Price
             mean    max   min       mean max
0     4866.000000   4866    11  11.000000  11
1     3113.000000   3113     6   6.000000   6
2     9568.000000   9568     9   9.000000   9
3     8170.000000   8170    13  13.000000  13
4    10199.000000  10199    11  11.000000  11
..            ...    ...   ...        ...  ..
243   6222.666667   7827    20  20.333333  21
244   7497.000000   7497     6   6.000000   6
245  19720.000000  19720     8   8.000000   8
246  16990.000000  16990    27  27.000000  27
247    128.500000    220     6  11.500000  17

[248 rows x 10 columns]

In [15]:
df_books.groupby('Author')[['User Rating','Reviews','Price']].agg({'Reviews':['min','max'],
                                                                   'User Rating':'sum',
                                                                   'Price':'mean'}).reset_index()

                         Author Reviews        User Rating      Price
                                    min    max         sum       mean
0              Abraham Verghese    4866   4866         9.2  11.000000
1                Adam Gasiewski    3113   3113         4.4   6.000000
2                 Adam Mansbach    9568   9568         4.8   9.000000
3                     Adir Levy    8170   8170         4.8  13.000000
4    Admiral William H. McRaven   10199  10199         4.7  11.000000
..                          ...     ...    ...         ...        ...
243             Walter Isaacson    3014   7827        13.7  20.333333
244               William Davis    7497   7497         8.8   6.000000
245            William P. Young   19720  19720         9.2   8.000000
246            Wizards RPG Team   16990  16990        14.4  27.000000
247                Zhi Gang Sha      37    220         9.2  11.500000

[248 rows x 5 columns]

In [16]:
df_books.groupby('Author')[['User Rating','Reviews','Price']].agg(rating_maximo=('User Rating','max'),
                                                                   precio_promedio=('Price','mean')).reset_index()

                         Author  rating_maximo  precio_promedio
0              Abraham Verghese            4.6        11.000000
1                Adam Gasiewski            4.4         6.000000
2                 Adam Mansbach            4.8         9.000000
3                     Adir Levy            4.8        13.000000
4    Admiral William H. McRaven            4.7        11.000000
..                          ...            ...              ...
243             Walter Isaacson            4.6        20.333333
244               William Davis            4.4         6.000000
245            William P. Young            4.6         8.000000
246            Wizards RPG Team            4.8        27.000000
247                Zhi Gang Sha            4.6        11.500000

[248 rows x 3 columns]

# AGRUPACIÓN POR 2 COLUMNAS

In [17]:
df_books.groupby(['Year','Genre']).count().reset_index()

    Year        Genre  Name  Author  User Rating  Reviews  Price
0   2009      Fiction    24      24           24       24     24
1   2009  Non Fiction    26      26           26       26     26
2   2010      Fiction    20      20           20       20     20
3   2010  Non Fiction    30      30           30       30     30
4   2011      Fiction    21      21           21       21     21
5   2011  Non Fiction    29      29           29       29     29
6   2012      Fiction    21      21           21       21     21
7   2012  Non Fiction    29      29           29       29     29
8   2013      Fiction    24      24           24       24     24
9   2013  Non Fiction    26      26           26       26     26
10  2014      Fiction    29      29           29       29     29
11  2014  Non Fiction    21      21           21       21     21
12  2015      Fiction    17      17           17       17     17
13  2015  Non Fiction    33      33           33       33     33
14  2016      Fiction    19      19           19       19     19
15  2016  Non Fiction    31      31           31       31     31
16  2017      Fiction    24      24           24       24     24
17  2017  Non Fiction    26      26           26       26     26
18  2018      Fiction    21      21           21       21     21
19  2018  Non Fiction    29      29           29       29     29
20  2019      Fiction    20      20           20       20     20
21  2019  Non Fiction    30      30           30       30     30