In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("taeefnajib/used-car-price-prediction-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/used-car-price-prediction-dataset

In [2]:
! ls /kaggle/input/used-car-price-prediction-dataset

used_cars.csv

In [3]:
DATASET_PATH = path + '/used_cars.csv'
# /kaggle/input/used-car-price-prediction-dataset/used_cars.csv

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
sns.set(style='whitegrid',context='notebook')

In [14]:
df = pd.read_csv(DATASET_PATH)
df.head(2)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"

# EDA

In [15]:
df.dtypes

brand           object
model           object
model_year       int64
milage          object
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

In [17]:
df.dtypes.value_counts()

object    11
int64      1
Name: count, dtype: int64

In [18]:
df.shape

(4009, 12)

In [19]:
df.isnull().sum().sum()

np.int64(879)

In [20]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [21]:
df.dropna(inplace=True)
df.shape

(3269, 12)

# CONVERTIR DATOS CATEGORICOS A NÚMERICOS

In [24]:
# Converting column data types
df['model_year'] = df['model_year'].astype('int64')

# Remove non-numeric characters from 'milage' and convert to float
df['milage'] = df['milage'].str.replace(',', '').str.replace(' mi.', '', regex=False).astype('float64')

# Remove non-numeric characters from 'price' and convert to float
df['price'] = df['price'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype('float64')

# Print the data types to verify the changes
df.dtypes

brand            object
model            object
model_year        int64
milage          float64
fuel_type        object
engine           object
transmission     object
ext_col          object
int_col          object
accident         object
clean_title      object
price           float64
dtype: object

In [25]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0
6,Audi,S3 2.0T Premium Plus,2017,84000.0,Gasoline,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,None reported,Yes,31000.0
7,BMW,740 iL,2001,242000.0,Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,None reported,Yes,7300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4003,Mercedes-Benz,E-Class E 300 4MATIC,2018,53705.0,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,Yes,25900.0
4004,Bentley,Continental GT Speed,2023,714.0,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,349950.0
4005,Audi,S4 3.0T Premium Plus,2022,10900.0,Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,53900.0
4007,Ford,F-150 Raptor,2020,33000.0,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,62999.0
4008,BMW,X3 xDrive30i,2020,43000.0,Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,40000.0

# REVISAMOS COLUMNAS CATEGORICAS

In [26]:
categorical_columns = df.select_dtypes(object).columns
categorical_columns

Index(['brand', 'model', 'fuel_type', 'engine', 'transmission', 'ext_col',
       'int_col', 'accident', 'clean_title'],
      dtype='object')

In [27]:
for cc in categorical_columns:
  print("*"*50)
  print(df[cc].value_counts())

**************************************************
brand
Ford             341
BMW              316
Mercedes-Benz    268
Chevrolet        259
Toyota           171
Porsche          158
Audi             153
Lexus            136
Jeep             114
Land             100
Nissan            95
Cadillac          92
GMC               84
Dodge             84
RAM               72
Subaru            59
Hyundai           57
Mazda             57
INFINITI          54
Volkswagen        51
Honda             49
Kia               46
Acura             45
Lincoln           44
Jaguar            39
Volvo             33
MINI              31
Maserati          31
Bentley           27
Buick             25
Chrysler          25
Mitsubishi        20
Genesis           16
Hummer            16
Pontiac           15
Lamborghini       15
Alfa              12
Rolls-Royce       10
Ferrari            9
Aston              8
Scion              6
Saturn             5
FIAT               4
McLaren            4
Mercury            3
Lotus              3
Saab               2
Bugatti            1
Plymouth           1
smart              1
Maybach            1
Suzuki             1
Name: count, dtype: int64
**************************************************
model
M3 Base               29
Corvette Base         22
F-150 XLT             22
Camaro 2SS            17
Mustang GT Premium    16
                      ..
Q7 45 Premium Plus     1
LX 470 Base            1
Escape Limited         1
RAV4 TRD Off Road      1
428 i xDrive           1
Name: count, Length: 1614, dtype: int64
**************************************************
fuel_type
Gasoline          2815
Hybrid             145
E85 Flex Fuel      128
Diesel             102
–                   44
Plug-In Hybrid      33
not supported        2
Name: count, dtype: int64
**************************************************
engine
355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel             48
420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel             46
–                                                        44
300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel    42
240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel             42
                                                         ..
362.0HP 5.4L 8 Cylinder Engine Gasoline Fuel              1
134.0HP 1.8L 4 Cylinder Engine Plug-In Electric/Gas       1
120.0HP 2.2L 4 Cylinder Engine Flex Fuel Capability       1
715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel             1
282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel              1
Name: count, Length: 963, dtype: int64
**************************************************
transmission
A/T                                  939
8-Speed A/T                          391
Transmission w/Dual Shift Mode       389
6-Speed A/T                          354
6-Speed M/T                          238
7-Speed A/T                          201
10-Speed A/T                         115
5-Speed A/T                           84
9-Speed A/T                           73
4-Speed A/T                           72
CVT Transmission                      62
8-Speed Automatic                     62
5-Speed M/T                           57
6-Speed Automatic                     39
M/T                                   38
10-Speed Automatic                    35
Automatic                             30
9-Speed Automatic                     26
Automatic CVT                         11
7-Speed M/T                            9
7-Speed Automatic with Auto-Shift      8
Transmission Overdrive Switch          7
6-Speed Manual                         5
8-Speed Automatic with Auto-Shift      5
6-Speed Automatic with Auto-Shift      4
5-Speed Automatic                      4
7-Speed Automatic                      3
4-Speed Automatic                      3
–                                      2
7-Speed Manual                         1
7-Speed                                1
7-Speed DCT Automatic                  1
Name: count, dtype: int64
**************************************************
ext_col
Black                        802
White                        731
Gray                         441
Silver                       335
Blue                         310
                            ...
Black Sapphire Metallic        1
Brilliant Silver Metallic      1
Glacier Silver Metallic        1
Nightfall Gray Metallic        1
C / C                          1
Name: count, Length: 120, dtype: int64
**************************************************
int_col
Black              1680
Beige               499
Gray                431
Brown               151
Red                 116
                   ...
Medium Ash Gray       1
White / Brown         1
Hotspur Hide          1
Canberra Beige        1
Deep Chestnut         1
Name: count, Length: 74, dtype: int64
**************************************************
accident
None reported                             2332
At least 1 accident or damage reported     937
Name: count, dtype: int64
**************************************************
clean_title
Yes    3269
Name: count, dtype: int64

In [ ]:
# prompt: la columna accident es categorica y tiene estos valores 'None reported' y 'At least 1 accident or damage reported' codificala 0 para el primero y 1 para el 2do caso y conviertela a int64

df['accident'] = df['accident'].map({'None reported': 0, 'At least 1 accident or damage reported': 1})
df['accident'] = df['accident'].astype('int64')

In [30]:
# prompt: analiza la columna transmission y encuentra un patron que permita codificar solo el valores 0 y 1 por el tipo de transimision comun po rjemplo une todoso lso que digan manual en 0 y automatico en 1

import numpy as np
# Analyze the 'transmission' column and create a binary encoding
# Identify values that represent 'Manual' and 'Automatic' transmissions
manual_keywords = ['Manual']
automatic_keywords = ['Automatic']

# Create the new binary column
df['transmission_encoded'] = np.nan  # Initialize with NaN

# Encode Manual transmissions as 0
for keyword in manual_keywords:
  df.loc[df['transmission'].str.contains(keyword, case=False, na=False), 'transmission_encoded'] = 0

# Encode Automatic transmissions as 1
for keyword in automatic_keywords:
    df.loc[df['transmission'].str.contains(keyword, case=False, na=False), 'transmission_encoded'] = 1

# Verify the changes
print("\nValue counts for original 'transmission' column:")
print(df['transmission'].value_counts())
print("\nValue counts for new 'transmission_encoded' column:")
print(df['transmission_encoded'].value_counts(dropna=False)) # Include NaN counts
print("\nFirst few rows with the new column:")
print(df[['transmission', 'transmission_encoded']].head())

# You might want to handle any remaining NaN values in 'transmission_encoded'
# depending on your requirements (e.g., drop rows or fill with a placeholder)
# Example: Drop rows where transmission_encoded is NaN
# df.dropna(subset=['transmission_encoded'], inplace=True)

Value counts for original 'transmission' column:
transmission
A/T                                  939
8-Speed A/T                          391
Transmission w/Dual Shift Mode       389
6-Speed A/T                          354
6-Speed M/T                          238
7-Speed A/T                          201
10-Speed A/T                         115
5-Speed A/T                           84
9-Speed A/T                           73
4-Speed A/T                           72
CVT Transmission                      62
8-Speed Automatic                     62
5-Speed M/T                           57
6-Speed Automatic                     39
M/T                                   38
10-Speed Automatic                    35
Automatic                             30
9-Speed Automatic                     26
Automatic CVT                         11
7-Speed M/T                            9
7-Speed Automatic with Auto-Shift      8
Transmission Overdrive Switch          7
6-Speed Manual                         5
8-Speed Automatic with Auto-Shift      5
6-Speed Automatic with Auto-Shift      4
5-Speed Automatic                      4
7-Speed Automatic                      3
4-Speed Automatic                      3
–                                      2
7-Speed Manual                         1
7-Speed                                1
7-Speed DCT Automatic                  1
Name: count, dtype: int64

Value counts for new 'transmission_encoded' column:
transmission_encoded
NaN    3032
1.0     231
0.0       6
Name: count, dtype: int64

First few rows with the new column:
        transmission  transmission_encoded
0        6-Speed A/T                   NaN
1  8-Speed Automatic                   1.0
3        7-Speed A/T                   NaN
6        6-Speed A/T                   NaN
7                A/T                   NaN

In [32]:
# prompt: renombra la columna transmission_encoded por automatic y reemplaza los Nan por 0

df = df.rename(columns={'transmission_encoded': 'automatic'})
df['automatic'] = df['automatic'].fillna(0)
print("\nValue counts for the renamed and filled 'automatic' column:")
print(df['automatic'].value_counts(dropna=False))
print("\nFirst few rows with the renamed column and filled NaNs:")
print(df[['transmission', 'automatic']].head())

Value counts for the renamed and filled 'automatic' column:
automatic
0.0    3038
1.0     231
Name: count, dtype: int64

First few rows with the renamed column and filled NaNs:
        transmission  automatic
0        6-Speed A/T        0.0
1  8-Speed Automatic        1.0
3        7-Speed A/T        0.0
6        6-Speed A/T        0.0
7                A/T        0.0

In [33]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,automatic
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,1,Yes,10300.0,0.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,1,Yes,38005.0,1.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,0,Yes,15500.0,0.0
6,Audi,S3 2.0T Premium Plus,2017,84000.0,Gasoline,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,0,Yes,31000.0,0.0
7,BMW,740 iL,2001,242000.0,Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,0,Yes,7300.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,Mercedes-Benz,E-Class E 300 4MATIC,2018,53705.0,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,1,Yes,25900.0,0.0
4004,Bentley,Continental GT Speed,2023,714.0,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,0,Yes,349950.0,1.0
4005,Audi,S4 3.0T Premium Plus,2022,10900.0,Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,0,Yes,53900.0,0.0
4007,Ford,F-150 Raptor,2020,33000.0,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,0,Yes,62999.0,0.0
4008,BMW,X3 xDrive30i,2020,43000.0,Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,1,Yes,40000.0,0.0

In [34]:
# prompt: analiza la columna engine y encuentra el nro que esta antes de la letra "L" por ejemplo "3.7L" y solo captura el numero y conviertelo a float64

df['engine'] = df['engine'].str.extract(r'(\d+\.?\d*)L').astype('float64')

In [35]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,automatic
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,3.7,6-Speed A/T,Black,Black,1,Yes,10300.0,0.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8,8-Speed Automatic,Moonlight Cloud,Gray,1,Yes,38005.0,1.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,3.5,7-Speed A/T,Black,Black,0,Yes,15500.0,0.0
6,Audi,S3 2.0T Premium Plus,2017,84000.0,Gasoline,2.0,6-Speed A/T,Blue,Black,0,Yes,31000.0,0.0
7,BMW,740 iL,2001,242000.0,Gasoline,4.4,A/T,Green,Green,0,Yes,7300.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,Mercedes-Benz,E-Class E 300 4MATIC,2018,53705.0,Gasoline,2.0,A/T,Black,Black,1,Yes,25900.0,0.0
4004,Bentley,Continental GT Speed,2023,714.0,Gasoline,6.0,8-Speed Automatic with Auto-Shift,C / C,Hotspur,0,Yes,349950.0,1.0
4005,Audi,S4 3.0T Premium Plus,2022,10900.0,Gasoline,3.0,Transmission w/Dual Shift Mode,Black,Black,0,Yes,53900.0,0.0
4007,Ford,F-150 Raptor,2020,33000.0,Gasoline,3.5,A/T,Blue,Black,0,Yes,62999.0,0.0
4008,BMW,X3 xDrive30i,2020,43000.0,Gasoline,2.0,A/T,Gray,Brown,1,Yes,40000.0,0.0

In [36]:
# prompt: crea otro dataframe llamado df_cleaned que solo tenga los valore snumericos del dataframe df

import numpy as np
df_cleaned = df.select_dtypes(include=np.number)
df_cleaned.head()

   model_year    milage  engine  accident    price  automatic
0        2013   51000.0     3.7         1  10300.0        0.0
1        2021   34742.0     3.8         1  38005.0        1.0
3        2015   88900.0     3.5         0  15500.0        0.0
6        2017   84000.0     2.0         0  31000.0        0.0
7        2001  242000.0     4.4         0   7300.0        0.0

In [37]:
# prompt: guarda el dataset df_cleaned en un archivo csv llamado cars_cleaned.csv

df_cleaned.to_csv('cars_cleaned.csv', index=False)